name: 'Test composite'
description: 'Greet someone'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
outputs:
  version:
    description: "Version"
    value: ${{ steps.get_version_from_changelog.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: get_version_from_changelog
      id: get_version_from_changelog
      run: |
        test ! -z "$KEY"
        if [ -z "$VERSION" ]; then
          VERSION=$(cat CHANGELOG.md | sed -r -e "/##\s+.*\[$KEY-[0-9]+\.[0-9]+\.[0-9]+\]/!d" -e "s/.*$KEY-([0-9]+\.[0-9]+\.[0-9]+).*/\1/" | sort --version-sort --reverse | head -n 1)
          test ! -z "$VERSION"
        fi
        echo "version: $VERSION"
        echo "version=$(echo $VERSION)" >> $GITHUB_OUTPUT

    # - name: Random Number Generator
    #   id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash

    # - name: Set GitHub Path
    #   run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    #   shell: bash
    #   env:
    #     GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: Run goodbye.sh
    #   run: goodbye.sh
    #   shell: bash
