name: QEMU Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-qemu:
    uses: ./.github/workflows/qemu-build-deploy.yml

  test-qemu:
    needs: build-qemu
    runs-on: ubuntu-latest
    env:
      TF_VAR_NAME: ${{ secrets.NAME }}
      TF_VAR_TYPE: ${{ secrets.TYPE }}
      TF_VAR_DISTRO: ${{ secrets.DISTRO }}
      TF_VAR_GUI_ACCESS: ${{ secrets.GUI_ACCESS }}
      TF_VAR_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Terraform build
        run: |
          terraform init
          terraform apply -auto-approve

  test-qemu-cleanup:
    needs: test-qemu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Terraform destroy
        run: |
          terraform destroy -auto-approve
