name: CI Pipeline

on:
  workflow_call

env:
  GUI_ACCESS: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      # - name: Run packer init
      #   id: init
      #   run: packer init ./image.pkr.hcl

      # - name: Run packer validate
      #   id: validate
      #   run: packer validate ./image.pkr.hcl

      - name: Install Packer Plugins
        run: |
          packer plugins install github.com/hashicorp/qemu
          packer plugins install github.com/hashicorp/virtualbox
          packer plugins install github.com/hashicorp/vagrant

  # todo check this
  upload-image-to-openstack:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Image to OpenStack
        run: |
          openstack image create --file target-qemu/* \
          --property hw_scsi_model=virtio-scsi \
          --property hw_disk_bus=scsi \
          --property hw_rng_model=virtio \
          --property hw_qemu_guest_agent=yes \
          --property os_require_quiesce=yes \
          --property os_type=$TYPE \
          --property os_distro=$DISTRO \
          --property owner_specified.openstack.version=$VERSION \
          --property owner_specified.openstack.gui_access=$GUI_ACCESS \
          --property owner_specified.openstack.created_by=munikypo \
          --shared ${{ github.event.repository.name }}-$VERSION

  git-tag:
    runs-on: ubuntu-latest
    needs: upload-image-to-openstack
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "github-actions@github.com"

      - name: Create and Push Git Tag
        run: |
          git tag -a "$KEY-$VERSION" -m "$KEY version $VERSION"
          git push origin "$KEY-$VERSION"

  get-version-from-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version from Changelog
        run: |
          test ! -z "$KEY"
          if [ -z "$VERSION" ]; then
            VERSION=$(grep -oP "##\s+.*\[$KEY-[0-9]+\.[0-9]+\.[0-9]+\]" CHANGELOG.md | \
              sed -r "s/.*$KEY-([0-9]+\.[0-9]+\.[0-9]+).*/\1/" | \
              sort -V | tail -n 1)
            test ! -z "$VERSION"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  upload-image-to-openstack-object-store:
    runs-on: ubuntu-latest
    needs: get-version-from-changelog
    steps:
      - name: Upload Image to OpenStack Object Store
        run: |
          cd target-qemu
          IMAGE_FILENAME=$(ls)
          mv $IMAGE_FILENAME $IMAGE_FILENAME.raw

          s3cmd -c $S3_CREDENTIALS get s3://kypo-images/SHA256SUMS SHA256SUMS
          s3cmd -c $S3_CREDENTIALS get s3://kypo-images/MD5SUMS MD5SUMS

          zip ${{ github.event.repository.name }}.raw.zip $IMAGE_FILENAME.raw
          sed -i "/${{ github.event.repository.name }}.raw.zip/d" SHA256SUMS
          sha256sum ${{ github.event.repository.name }}.raw.zip >> SHA256SUMS
          sed -i "/${{ github.event.repository.name }}.raw.zip/d" MD5SUMS
          md5sum ${{ github.event.repository.name }}.raw.zip >> MD5SUMS

          qemu-img convert -f raw -O qcow2 $IMAGE_FILENAME.raw ${{ github.event.repository.name }}.qcow2
          sed -i "/${{ github.event.repository.name }}.qcow2/d" SHA256SUMS
          sha256sum ${{ github.event.repository.name }}.qcow2 >> SHA256SUMS
          sed -i "/${{ github.event.repository.name }}.qcow2/d" MD5SUMS
          md5sum ${{ github.event.repository.name }}.qcow2 >> MD5SUMS

          sort -k 2 -o SHA256SUMS SHA256SUMS
          sort -k 2 -o MD5SUMS MD5SUMS
          s3cmd -c $S3_CREDENTIALS put ${{ github.event.repository.name }}.qcow2 ${{ github.event.repository.name }}.raw.zip SHA256SUMS MD5SUMS s3://kypo-images
          cd -
